[package]
name = "end2-api-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
anyhow = "1.0.100"
base64.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
vodozemac.workspace = true
