[package]
name = "thesischain"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3
debug = 2

[profile.dev.build-override]
opt-level = 3

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"

[dependencies]
axum = { version = "0.8", features = ["macros"] }
base64 = "0.22.1"
blake3 = { version = "1.8.2", features = ["serde"] }
chrono = "0.4.42"
hkdf = { version = "0.12.4", features = ["std"] }
libp2p = { version = "0.56.0", features = ["mdns", "noise", "quic", "tokio"] }
p256 = { version = "0.13.2", features = ["ecdh", "ecdsa", "serde"] }
rand_core = { version = "0.6.4", features = ["getrandom"] }
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
sha2 = "0.10.9"
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["chrono", "env-filter"] }
