[package]
name = "pki-chains"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
axum = "0.8"
futures = "0.3.31"
libp2p = { version = "0.56", features = ["gossipsub", "macros", "mdns", "noise", "quic", "tcp", "tokio", "yamux"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
