[package]
name = "thesischain"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
anyhow = "1"
blake3 = "1"
chrono = { version = "0.4", features = ["serde"] }
env = "1"
env_logger = "0.11"
futures = "0.3"
hex = "0.4"
k256 = { version = "0.13", features = ["ecdsa", "ecdh", "serde"] }
log = "0.4"
rand = "0.8"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = { version = "3", features = ["hex"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
