[package]
name = "thesischain"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 0
debug = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3
debug = 2

[profile.dev.build-override]
opt-level = 3

[profile.release]
strip = "symbols"
lto = "thin"
panic = "abort"

[dependencies]
axum = "0.8"
blake3 = { version = "1.8.2", features = ["serde"] }
chrono = "0.4.42"
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1.0.145"
tokio = { version = "1", features = ["full"] }
tower = "0.5.2"
