services:
  database:
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - ${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - end2-network

  nginx:
    image: nginx:1.29-alpine
    restart: unless-stopped
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/ssl:/etc/ssl/certs:ro
    networks:
      - end2-network

  tunnel:
    image: cloudflare/cloudflared
    env_file:
      - .env
    restart: unless-stopped
    command: tunnel run
    depends_on:
      - nginx
    networks:
      - end2-network

  backend:
    build:
      context: ./crates/end2
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@database:${DB_PORT}/${DB_NAME}"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - end2-network

  frontend:
    build:
      context: ./crates/end2-wasm-client
    env_file:
      - .env
    networks:
      - end2-network

volumes:
  pg_data:
networks:
  end2-network:
    driver: bridge