[package]
name = "defs"
version = "0.0.0"
edition.workspace = true

[lib]
doctest = false

[dependencies]
bincode.workspace = true
ed25519-dalek.workspace = true
generic-array = { version = "0.14.7", features = ["serde"] }
serde.workspace = true
sha2.workspace = true
x25519-dalek.workspace = true
